### ISSUE TITLE
what's the difference between control_domain and remote_host	?

### ISSUE THREAD

**Issue by mebest100** [projectarkc/arkc-server#1]

**Comment by NoahArkc** [comment]
Sorry for being unclear. We're improve / updating readme and FAQ.

The client will send a string to one of the dns_server and query for an A
record like:

XXXXXXXXXXXX.XXXXXX.XXXXX."control_domain". The NS record of the
control_domain is set to your VPS.

E.g. In testing, I use control_domain = "testing.arkc.org", and set NS
record to my test VPS.

In this case, the actual IP of the server is hidden, as long as the server
connects to the client via a proxy / MEEK.

And if you don't want to configure a domain, it's OK. Please set the
dns_server to your VPS IP and port 53, and fill "something.com" into
control_domain.

"remote_host" often needn't be set. Its default value at client side is
"0.0.0.0". It means you will listen for any connection from the server (and
authenticate later).

Local listen address is specified by "local_host" and "local_port". When
unspecified, it goes to 127.0.0.1:8001. Without [-ep] enabled it is HTTP
proxy.

For the UPnP part:

"Mismatched address" means you may have multiple layers of NAT, e.g., you
connect to a WiFi router and it further connects to a router of your ISP.
So far UPnP cannot process multiple layers and we're working on TCP hole
punching. Please configure it manually on the routers, or connect to the
ISP router directly.

E.g.:

Your IP = 192.168.1.5 ---> Wifi router 1 192.168.1.1 NAT=> 192.168.18.5 -->
ISP router 192.168.18.1 NAT=> 110.110.110.110.

Best regards,

Sincerely,
Noah

**Comment by mebest100** [comment]
Hi  NoahArkc,
Thanks a lot for your quick reply.
But so regretly for upnp, because I hv no independent public IP from ISP,hence it's impossible for me to mapping NAT manually and also the procedures is really too complex and hard for me , I am not able to finish it. 
Can I just disable UPNP function from client   ?

Thanks !

**Comment by NoahArkc** [comment]
Hi, Yuan78,

I understand your situation. I am so sorry to hear that.

Disable UPnP takes command line option [-pn]. But if you disable it, your
VPS may not connect to you at home! There are the evil NATs in between.

If you wish to find an option to go directly from client to server, it may
be a better idea to wait a moment! We're trying to tackle NAT traversal
(against the ISPs like yours) and it takes a moment. (We're debugging it
right now in a room!) Could we contact you via email then, when we're done
with that function? It may be done in this weekend.

We really need to collect samples with ISPs like yours, so your
participation will be a great help!

Best regards,

Sincerely,
Noah

**Comment by mebest100** [comment]
Hi Noaharkc,
Thank a lot for your hard work and wait for your good news!
 anyway hv a nice day!

2016-03-04 21:05 GMT+08:00, NoahArkc notifications@github.com:

> Hi, Yuan78,
> 
> I understand your situation. I am so sorry to hear that.
> 
> Disable UPnP takes command line option [-pn]. But if you disable it, your
> VPS may not connect to you at home! There are the evil NATs in between.
> 
> If you wish to find an option to go directly from client to server, it may
> be a better idea to wait a moment! We're trying to tackle NAT traversal
> (against the ISPs like yours) and it takes a moment. (We're debugging it
> right now in a room!) Could we contact you via email then, when we're done
> with that function? It may be done in this weekend.
> 
> We really need to collect samples with ISPs like yours, so your
> participation will be a great help!
> 
> Best regards,
> 
> Sincerely,
> Noah
>
