### ISSUE TITLE
A clear first-time user guide

### ISSUE THREAD

**Issue by tonyyanga** [projectarkc/arkc-server#2]
Hi, I am back.

I am writing to remind you that the testing service keys in https://arkc.org/2015/12/17/open-testing-service/ is no longer available. 404 Error.

ArkC is a good solution, but I think it will be better if it includes a better guide for first-time user. ArkC has docs about its options, but one cannot start using it in this way! He needs a step-by-step guide.

**Comment by NoahArkc** [comment]
Hi,

We've updated the test service notice.

Best regards,

Sincerely,
Noah
